version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/app:/app
    command: ["npm", "run", "dev", "--", "--host"]
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/app
      - /app/node_modules
    environment:
      - FLASK_ENV=development
    command: ["gunicorn", "--bind", "0.0.0.0:3000", "app:app"]
    depends_on:
      - frontend
      
      
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    volumes:
      - ./auth/app:/app
      - /app/node_modules
    environment:
      - FLASK_ENV=development
    command: ["gunicorn", "--bind", "0.0.0.0:6969", "app:app"]
    depends_on:
      - frontend
